### ISSUE TITLE
add CI to check env name collisions

### ISSUE THREAD

**Issue by bap2pecs** [Snapchain/op-chain-deployment#16]
there are

- .env.example
- .env.bridge.example
- .env.explorer.example

they shouldn't contain ENVs that have the same names or it might cause problems

for example, in `scripts/l2-explorer/l2-explorer-start.sh`

we have

```
# Source the .env.explorer file
set -a
source $(pwd)/.env
source $(pwd)/.env.explorer
set +a
```

**Comment by lesterli** [comment]
closed https://github.com/Snapchain/op-chain-deployment/pull/20
